# Jekyll configuration
exclude: ["CNAME", "Makefile", "README.md", "default.nix"]
permalink: /posts/:title/
future: false

# Site configuration
title: The Spinning Arrow
description: Not all those who wander are lost.
