# Jekyll configuration
exclude: ["new_post.sh", "CNAME", "README.md"]
markdown: kramdown
highlighter: pygments
permalink: /posts/:title

# Site configuration
title: The Spinning Arrow
description: Not all those who wander are lost.
