# Jekyll configuration
exclude: ["new_post.sh", "CNAME", "README.md"]
permalink: /posts/:title/
future: true

# Site configuration
title: The Spinning Arrow
description: Not all those who wander are lost.
